INSERT INTO USERS (ID, AGE, FIRST_NAME, LAST_NAME, OCCUPATION) VALUES (10001, 25, 'ANNA', 'MONTANA', 'JOURNALIST');
INSERT INTO USERS (ID, AGE, FIRST_NAME, LAST_NAME, OCCUPATION) VALUES (10002, 24, 'KENNEDY', 'BARBERA', 'PILOT');
INSERT INTO USERS (ID, AGE, FIRST_NAME, LAST_NAME, OCCUPATION) VALUES (10003, 45, 'THOMAS', 'NJOROGE', 'BUSINESS MAN');
